

services:
  web:
    depends_on:
      - redis
      - restaurant_service
      - payment_service
      - delivery_service

    build: ./food_ordering_system

    ports:
      - 5173:5173

    env_file:
       - ./food_ordering_system/.env

    develop:
      watch:
        - path: ./food_ordering_system/package.json
          action: rebuild
        - path: ./food_ordering_system/package-lock.json
          action: rebuild

        - path: ./food_ordering_system
          target: /app
          action: sync

  restaurant_service:
    build: ./microservices/restaurant_service
    container_name: restaurant_service

    ports:
      - 5001:5001

    env_file:
      - ./microservices/restaurant_service/.env

    develop:
      watch:
        - path: ./microservices/restaurant_service/package.json
          action: rebuild
        - path: ./microservices/restaurant_service/package-lock.json
          action: rebuild

        - path: ./microservices/restaurant_service/.env
          target: /app
          action: sync
  delivery_service:
    build: ./microservices/delivery_service
    container_name: delivery_service

    ports:
      - 5000:5000

    env_file:
      - ./microservices/delivery_service/.env

    develop:
      watch:
        - path: ./microservices/delivery_service/package.json
          action: rebuild
        - path: ./microservices/delivery_service/package-lock.json
          action: rebuild

        - path: ./microservices/delivery_service/.env
          target: /app
          action: sync

  payment_service:
    build: ./microservices/payment_service
    container_name: payment_service

    ports:
      - 5002:5002

    env_file:
      - ./microservices/payment_service/.env

    develop:
      watch:
        - path: ./microservices/payment_service/package.json
          action: rebuild
        - path: ./microservices/payment_service/package-lock.json
          action: rebuild

        - path: ./microservices/payment_service/.env
          target: /app
          action: sync
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
