apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery-service
  ports:
    - protocol: TCP
      port: 5000        # Kubernetes service port
      targetPort: 5000  # Container port
  type: ClusterIP       # Can be NodePort if you want direct access
