apiVersion: v1
kind: ConfigMap
metadata:
  name: ordering-service-config
data:

 PORT: "5003"
 MONGO_DB_URL: "mongodb+srv://admin:PWDLtqNoe2ld4Hjm@restbackend.vfbr0.mongodb.net/?retryWrites=true&w=majority&appName=RESTBackend"
 JWT_SECRET: "SECRET_CODE"
 FRONTEND_PREFIX: " http://localhost:5173"
 STRIPE_SECRET: "sk_test_51RD4hYRvL565VgPE4dabCShkAOJNnFpKqJpm5OSzXfpvW2LBwaFnybgIaLWRvEtQWZIwuV5lRlCAudkcxAe91ZA800yxAIkRYe"
