apiVersion: v1
kind: Service
metadata:
  name: ordering-service
spec:
  selector:
    app: ordering-service
  ports:
    - protocol: TCP
      port: 5003      # Kubernetes service port
      targetPort: 5003  # Container port
  type: ClusterIP       # Can be NodePort if you want direct access
