apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 5001       # Kubernetes service port
      targetPort: 5001  # Container port
  type: ClusterIP       # Can be NodePort if you want direct access
