apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:

 PORT: "5001"
 MONGO_DB_URL: "mongodb+srv://admin:YrpBxqtSEngp7Za8@restbackend.vfbr0.mongodb.net/?retryWrites=true&w=majority&appName=RESTBackend"
 JWT_SECRET: "SECRET_CODE"
 VAPID_PUBLIC_KEY: "PLACEHOLDER"
 VAPID_PRIVATE_KEY: "PLACEHOLDER"
