apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant-service
  ports:
    - protocol: TCP
      port: 5002        # Kubernetes service port
      targetPort: 5002  # Container port
  type: ClusterIP       # Can be NodePort if you want direct access
